### ISSUE TITLE
Add datasource configurations to values.yaml

### ISSUE THREAD

**Issue by Savidude** [wso2/kubernetes-is#156]
**Description:**
Add configurations for MySQL datasources as follows to the values.yaml file in helm resources for all deployment patterns.

```
mysql:
    enabled: true
    host: wso2is-rdbms-service-mysql
    username: wso2carbon
    password: wso2carbon
    driverClass: com.mysql.jdbc.Driver
    validationQuery: "SELECT 1"
```

These values can be referred in the ConfigMap templates as follows:
```
{{- $config_dburl := printf "%s%s%s" "jdbc:mysql://" .Values.wso2.mysql.host ":3306/WSO2EI_INTEGRATOR_CONFIG_GOV_DB?autoReconnect=true&amp;useSSL=false" }}
{{- $user_dburl := printf "%s%s%s" "jdbc:mysql://" .Values.wso2.mysql.host ":3306/WSO2EI_USER_DB?autoReconnect=true&amp;useSSL=false" }}
{{- $db_driver_class_name := .Values.wso2.mysql.driverClass }}
{{- $db_validation_query := .Values.wso2.mysql.validationQuery }}
{{- $db_username := .Values.wso2.mysql.username }}
{{- $db_password := .Values.wso2.mysql.password }}
```

Additionally, the database host can be parameterized in the deployment template initContainers as follows:
```
command: ['sh', '-c', 'echo -e "Checking for the availability of MySQL Server deployment"; while ! nc -z {{ default "wso2ei-rdbms-service-mysql" .Values.wso2.mysql.host }} 3306; do sleep 1; printf "-"; done; echo -e "  >> MySQL Server has started";']
```

**Affected Product Version:**
 Helm resources for WSO2 Identity Server v5.8.x and below
