### ISSUE TITLE
[v5.10.x] external-nfs mount failure

### ISSUE THREAD

**Issue by winestein** [wso2/kubernetes-is#218]
**Description:**

Hi all!

I found a problem when deploying the advanced chart with a cloudProvider of type "external-nfs".
![image](https://user-images.githubusercontent.com/56927788/81072535-a87d4800-8ebc-11ea-9d2a-782705e8f39a.png)

The NFS (AWS EFS) volume fails to mount, since the defined paths in "sharedTenants" and "sharedUserstores" doesn't exist. Once I mounted the volume in an Ubuntu Pod and created the paths, everything worked normally.

The chart could be incremented to add a init check to see if the defined paths exist on the NFS? 

**Affected Product Version:** Chart "advanced/is-pattern-1" -  version 5.10.0-1

**OS, DB, other environment details and versions:**    

**Steps to reproduce:** Deploy the helm chart with the value "wso2.persistentRuntimeArtifacts.cloudProvider" set to "external-nfs" pointing to an instance of EFS on AWS;

Used configuration:

```yaml
persistentRuntimeArtifacts:
        # Persistent storage provider expected to be used for sharing persistent runtime artifacts
        # This can be one of the following.
        #   1. internal-nfs - Using the NFS dynamic provisioner for Kubernetes
        #   2. external-nfs - Using an externally configured NFS server
        cloudProvider: "external-nfs"
        # External NFS Server IP
        nfsServerIP: "<efs-domain>"
        # Exported location on external NFS Server to be mounted at <IS_HOME>/repository/tenants
        sharedTenants: "/tenants"
        # Exported location on external NFS Server to be mounted at <IS_HOME>/repository/deployment/server/userstores
        sharedUserstores: "/userstores"
```
