### ISSUE TITLE
[v5.10.x] Incorrect Input Value to Disable Evaluatory MySQL Helm Chart

### ISSUE THREAD

**Issue by chirangaalwis** [wso2/kubernetes-is#264]
**Description:**
It was noticed that IAM Pattern 1 Helm chart defines the following property to enable/disable the evaluatory MySQL deployment.

```
wso2:
  deployment:
    dependencies:
      # The configuration should be set to be 'true' if a MySQL database should be spawned as a pod within the cluster
      mysql: true
```

This is incorrect when compared with the expected `condition` path [`wso2.mysql.enabled`](https://github.com/wso2/kubernetes-is/blob/v5.10.0.2/advanced/is-pattern-1/requirements.yaml#L18).

**Suggested Solution:**
The `requirements.yaml` needs to be fixed by setting the correct `condition` path to `wso2.deployment.dependencies.mysql`.

**Suggested Workaround For Current Users:**
You may use the property `wso2.mysql.enabled` in the Helm chart installation (`helm install`) or (`helm upgrade`) release upgrade to enable/disable this property.

For example,
```
helm install <release-name> wso2/is-pattern-1 --version 5.10.0-2 --namespace <namespace> --set wso2.mysql.enabled=<true/false>
```

**Affected Product Version:**
Helm Resources for WSO2 IAM version `5.10.0.2` and below
